version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  build:
    context: .
    dockerfile: Dockerfile_spark
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - ELT

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres
  networks:
    - ELT

services:

  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"

  spark-worker-1:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-2:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  spark-worker-3:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - ELT

  webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-web-server
    hostname: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler
    restart: on-failure

  scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    hostname: scheduler
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Yusuf --lastname Ganiyu --role Admin --email airscholar@gmail.com --password admin && airflow scheduler"

  hbase:

    image: dajobe/hbase:latest
    container_name: hbase
    hostname: hbase
    environment:
      - HBASE_DATA_DIR=/data
      - HBASE_ROOTDIR=/hbase

    ports:
        - '16010:16010'
        - '9095:9095'
        - '8085:8085'
    networks:
        - ELT
    restart: unless-stopped

  


networks: 
  ELT:




 