FROM dajobe/hbase:latest

USER root

# Install OpenJDK-11 and Apache Ant
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean

# Set JAVA_HOME environment variable
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/


